name: Stylua

on:
  workflow_dispatch:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Stylua check
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --verbose .
          version: latest
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "chore: apply Stylua formatting"
            git push
          fi
